### ISSUE TITLE
Damat Kogusu (2017) filmindeki keltos

### ISSUE THREAD

**Issue by bbyalcinkaya** [MrGranddy/Kotu-Karakterler#1]
[Damat Kogusu](https://www.imdb.com/title/tt6101458/) filmindeki kel adamin (Adem Yilmaz) listeye eklenmesi gerektigini dusunuyorum. Sebepleri:
* Asiri korkunc bir karakter
* Kapasitesinin asiri ustunde bir kotulugu var

**Comment by MrGranddy** [comment]
Sırası ile birlikte formata uygun şekilde PR atarsanız ekleyebiliriz :)

**Comment by bbyalcinkaya** [comment]
Sirasini bilemiyorum. Once tartismak lazim.
